apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: chatapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatapi
  template:
    metadata:
      labels:
        app: chatapi 
    spec:
      containers:
      - name: nodeserver
        image: barath8302/node-app:1.0
        ports:
        - containerPort: 3000